### ISSUE TITLE
OurChat项目客户端出错

### ISSUE THREAD

**Issue by aosikaxuanzhuanshouzhuabing** [flyjay123/OurChat#3]
我是一位在学习QT的新手，我在编译你github的项目OurChat时程序出现了报错：
我可以成功连接到服务器，但是当我点击登录或注册按钮时，无法向服务端写入数据
我想请问一下这是什么原因导致的呢，我的QT版本是6.2.4，以下是报错截图
![image](https://github.com/flyjay123/OurChat/assets/44134282/503ce77a-874d-483f-851d-d2d924e38937)

**Comment by flyjay123** [comment]
看起来像是服务器的问题，如果你用了魔法可能会出现这种情况，如果没有，提供一下关于服务器的信息

**Comment by aosikaxuanzhuanshouzhuabing** [comment]
非常感谢楼主，我在关闭了梯子之后可以做到连接服务器了，感谢你的帮助.
